[oneAPI_Level_Zero_Headers]
git-tree-sha1 = "91a503a9d6e1401597f4a12f6745c08cfcef5190"

    [[oneAPI_Level_Zero_Headers.download]]
    sha256 = "3cd40591a97eb246be3cc9c5445aa542a0bbff3313a83524d303d84f931ba35d"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Level_Zero_Headers_jll.jl/releases/download/oneAPI_Level_Zero_Headers-v1.13.0+2/oneAPI_Level_Zero_Headers.v1.13.0.any.tar.gz"
